name: Prevent Accidental Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  guard:
    name: Guard against publishing steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Search for publish keywords in workflows
        run: |
          set -euo pipefail
          WORKFLOW_DIR=".github/workflows"
          
          echo "Scanning workflow files for publish-related keywords..."
          
          # Search for publish-related patterns
          MATCHES=$(find "$WORKFLOW_DIR" -type f -name "*.yml" -not -name "no-publish-guard.yml" -print0 | \
            xargs -0 grep -n -E "uv publish|twine upload|upload.*pypi|PyPI" || true)
          
          if [ -n "$MATCHES" ]; then
            echo "❌ ERROR: Potential publish-related strings found in workflows:"
            echo "$MATCHES"
            echo ""
            echo "This repository is configured to prevent accidental publishing."
            echo "If you need to add release automation, please:"
            echo "1. Create a separate branch for release configuration"
            echo "2. Ensure repository owners configure release secrets"
            echo "3. Update this guard workflow accordingly"
            exit 1
          fi

      - name: Success
        run: |
          echo "✅ No publish keywords found in workflows"
          echo "✅ Repository is protected from accidental publishing"
