name: Prevent accidental publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  guard:
    name: Guard against publishing steps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Search for publish keywords in workflows
        run: |
          set -euo pipefail
          # Only scan workflow files in .github/workflows (skip lockfiles and venv)
          WORKFLOW_DIR=".github/workflows"
          # Exclude this guard file from the search
          find "$WORKFLOW_DIR" -type f -name "*.yml" -not -name "no-publish-guard.yml" | \
            xargs -r git grep -n -- "uv publish\|twine upload\|upload to pypi\|pypi" || true
          # If any matches were printed, fail now
          if [ -n "$(find "$WORKFLOW_DIR" -type f -name "*.yml" -not -name "no-publish-guard.yml" -print0 | xargs -0 git grep -n -- "uv publish\|twine upload\|upload to pypi\|pypi" || true)" ]; then
            echo "Potential publish-related strings found in workflows. Please ensure publishing automation is intentional." >&2
            exit 1
          fi

      - name: OK
        run: echo "No publish keywords found"
